/**
 * An error generated by fetch.
 */
export default class FetchError extends Error {
  /**
   * Creat a fetch error.
   * @param {Response} response - The fetch response.
   * @param  {...any} params - Any other Error params.
   */
  constructor (response, ...params) {
    super(...params)

    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, FetchError)
    }

    this.name = 'FetchError'
    this.response = response
  }
}
